sudo: true
dist: trusty
notifications:
  email: false
jobs:
  include:
    - stage: build
      script:
      - echo "build stage"
      - echo "build stage" > test
    - stage: test
      script:
      - echo "test stage"
      - cat test
    - stage: mergetodev
      script: echo "merging"
      if: branch =~ ^[0-9]
