sudo: true
dist: trusty
language: node_js
node_js:
  - "8"
notifications:
  email: false
before_install:
  - cd labtool2.0
  - npm config set spin false
  - npm install -g npm
install:
  - npm install
jobs:
  include:
    - stage: build feature
      script:
      - npm test
      after_success:
      - echo "onnistumisen jälkeen ei tehdä konttia, mutta jotain muuta ehkä? "
      if: branch =~ ^[0-9]
    - stage: development
      script:
      - npm test
      after_success:
      - echo "tehdään development ympäristön kontti ja pushataan dockerhubiin"
      if: branch = dev
    - stage: master
      script:
      - npm test
      after_success:
      - echo "tehdään master ympäristön kontti ja pushataan dockerhubiin"
      if: branch = master