sudo: true
dist: trusty
notifications:
  email: false
jobs:
  include:
    - stage: build feature
      script:
      - cd labtool2.0
      - npm i -g npm
      - npm test
      after_success:
      - echo "suksessss"
      if: branch =~ ^[0-9]
    - stage: development
      script:
      - cd labtool2.0
      - npm i -g npm
      - npm test
      after_success:
      - echo "suksessss"
      - echo "tehdään development ympäristön kontti ja pushataan dockerhubiin"
      if: branch = dev
    - stage: master
      script:
      - cd labtool2.0
      - npm i -g npm
      - npm test
      after_success:
      - echo "suksessss"
      - echo "tehdään master ympäristön kontti ja pushataan dockerhubiin"
      if: branch = master