sudo: true
dist: trusty
notifications:
  email: false
jobs:
  include:
    - stage: build
      script:
      - echo "dummy login"
      if: branch =~ ^[0-9]
    - stage: test
      script: echo "testing"
