sudo: true
dist: trusty
language: node_js
node_js:
  - "8"
notifications:
  email: false
before_install:
  - "npm config set spin false"
  - "npm install -g npm"
install:
  - npm install
jobs:
  include:
    - stage: build feature
      script:
      - cd labtool2.0
      - npm test
      after_success:
      - echo "suksessss"
      if: branch =~ ^[0-9]
    - stage: development
      script:
      - cd labtool2.0
      - npm test
      after_success:
      - echo "suksessss"
      - echo "tehdään development ympäristön kontti ja pushataan dockerhubiin"
      if: branch = dev
    - stage: master
      script:
      - cd labtool2.0
      - npm test
      after_success:
      - echo "suksessss"
      - echo "tehdään master ympäristön kontti ja pushataan dockerhubiin"
      if: branch = master